import { describe, expect, it } from "vitest";

import * as ix from "../src/instructions.js";
import { ROLE } from "../src/instructions.js";
import { fixture, key } from "./fixture.js";

/**
 * The SDK and the on-chain builders must encode identical instructions. Both are compared against
 * one artifact generated by `program/tests/fixtures.rs`, so neither can drift without a red test.
 */

const programId = key(9);
const payer = key(10);
const indexMint = key(1);
const governor = key(2);
const manager = key(3);
const feeRecipient = key(4);
const componentA = key(5);
const componentB = key(6);
const user = key(11);
const userIndexAccount = key(12);
const feeAccount = key(13);
const userA = key(14);
const userB = key(15);
const bidder = key(16);
const componentMints = [componentA, componentB];
const components = [
  { mint: componentA, tokenAccount: userA },
  { mint: componentB, tokenAccount: userB },
];

const built: Record<string, ReturnType<typeof ix.sealIndex>> = {
  initIndex: ix.initIndex({
    programId,
    payer,
    indexMint,
    governor,
    manager,
    feeRecipient,
    name: "Flock DeFi Index",
    symbol: "FDI",
    streamingFeeBps: 95,
    issueFeeBps: 10,
    redeemFeeBps: 15,
    maxPremiumBps: 300,
    rebalanceDelay: 86_400,
  }),
  addComponent: ix.addComponent({
    programId,
    manager,
    payer,
    indexMint,
    componentMint: componentA,
    units: 1_234_567n,
  }),
  sealIndex: ix.sealIndex({ programId, manager, indexMint }),
  issue: ix.issue({
    programId,
    user,
    indexMint,
    userIndexAccount,
    feeAccount,
    components,
    amount: 5_000_000_000n,
    maxIn: [10_000_000n, 3_000_000_000n],
  }),
  redeem: ix.redeem({
    programId,
    user,
    indexMint,
    userIndexAccount,
    feeAccount,
    components,
    amount: 2_500_000_000n,
    minOut: [1n, 2n],
  }),
  accrueFees: ix.accrueFees({ programId, indexMint, feeAccount, componentMints }),
  proposeRebalance: ix.proposeRebalance({
    programId,
    manager,
    indexMint,
    componentMints,
    targetUnits: [2_000_000n, 500_000_000n],
    refPricesE9: [1_050_000_000n, 103_930_000_000n],
    duration: 7_200,
    startPremiumBps: -50,
    endPremiumBps: 150,
    maxNavLossBps: 100,
  }),
  bid: ix.bid({
    programId,
    bidder,
    indexMint,
    componentMints,
    bidderReceiveAccount: userA,
    bidderPayAccount: userB,
    sellComponent: 1,
    buyComponent: 0,
    sellAmount: 2_500_000_000n,
    maxBuyAmount: 251_250_000n,
  }),
  endRebalance: ix.endRebalance({ programId, caller: bidder, indexMint, componentMints }),
  setParams: ix.setParams({
    programId,
    governor,
    indexMint,
    streamingFeeBps: 95,
    issueFeeBps: 10,
    redeemFeeBps: 15,
    maxPremiumBps: 300,
    rebalanceDelay: 86_400,
  }),
  setAuthority: ix.setAuthority({
    programId,
    governor,
    indexMint,
    role: ROLE.manager,
    newAuthority: key(17),
  }),
  setPaused: ix.setPaused({ programId, caller: manager, indexMint, paused: true }),
};

describe("instruction parity with the on-chain builders", () => {
  it("covers every instruction the program exposes", () => {
    expect(Object.keys(built).sort()).toEqual(fixture.instructions.map((i) => i.name).sort());
  });

  for (const expected of fixture.instructions) {
    it(`${expected.name} encodes identically`, () => {
      const actual = built[expected.name];
      expect(actual, `no SDK builder for ${expected.name}`).toBeDefined();
      expect(actual!.programId.toBase58()).toBe(expected.programId);
      expect(actual!.data.toString("hex")).toBe(expected.dataHex);
      expect(
        actual!.keys.map((k) => ({
          pubkey: k.pubkey.toBase58(),
          isSigner: k.isSigner,
          isWritable: k.isWritable,
        })),
      ).toEqual(expected.accounts);
    });
  }
});
